# This rule is not used by the project autodelpoy-scaler itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to api.crazyfrank.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: autodelpoy-scaler
    app.kubernetes.io/managed-by: kustomize
  name: scaler-viewer-role
rules:
- apiGroups:
  - api.crazyfrank.com
  resources:
  - scalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.crazyfrank.com
  resources:
  - scalers/status
  verbs:
  - get
